<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__id</name>
   <tag></tag>
   <elementGuidId>99f4e2c0-564a-49de-bdb5-6659cb6e1c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bd07be7-0831-46b7-8966-d972f6c188d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1735536-2a4a-49c9-b3a3-15c6ce56e1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>아이디</value>
      <webElementGuid>f96c763f-2f9a-489c-8ac6-540af7f3476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>28f5ab75-e3f5-4d78-8bf0-efaddce09639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss1&quot;]/main[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg jss2 css-1qsxih2&quot;]/div[@class=&quot;loginView_login__3ILuY&quot;]/div[@class=&quot;loginView_inner__2oo9N&quot;]/form[1]/label[1]/input[1]</value>
      <webElementGuid>8e324a92-0104-4640-aad9-491cd5cb2220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='id']</value>
      <webElementGuid>86c34785-b288-46fb-b05b-fe0e565b45b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/form/label/input</value>
      <webElementGuid>dea0a02a-496a-43c2-bca3-9681d3bd4678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8e5580a5-1407-4f52-8022-4ad4a2661544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '아이디' and @name = 'id']</value>
      <webElementGuid>30eea8d9-17c2-4f35-b68c-50911cac38c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
