<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__layoutHeader_logo__8pZdM</name>
   <tag></tag>
   <elementGuidId>0bc8141c-8e59-4e8f-971a-17b1d1b7ec00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.layoutHeader_logo__8pZdM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>374f280f-d233-41ac-ba53-ab41cb607840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>393dd862-1eaf-4bb8-96a9-8cae083df13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layoutHeader_logo__8pZdM</value>
      <webElementGuid>0b3ab883-3dee-4431-99c8-7fb66c97d96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss4&quot;]/div[@class=&quot;layoutHeader_header_cim__1hvsL&quot;]/nav[1]/div[@class=&quot;layoutHeader_inner__ipM-g&quot;]/a[@class=&quot;layoutHeader_logo__8pZdM&quot;]</value>
      <webElementGuid>59c3c2e1-21c2-429a-8d20-4dcfaabdc848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/div/a</value>
      <webElementGuid>2c12df91-0681-4cfa-b550-0a82c4ce88de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='제품소개'])[1]/preceding::a[1]</value>
      <webElementGuid>569c50cb-2b6f-41ea-8e7b-53d850825c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='midas CIM'])[1]/preceding::a[2]</value>
      <webElementGuid>8182a58f-fcbe-4326-997d-edf76574e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/')]</value>
      <webElementGuid>0170a75d-927f-493d-97ed-6bf0e68a3506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d7becc36-608d-4182-9080-3e61f90d19d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/']</value>
      <webElementGuid>bca0cf03-d8d3-4ece-a811-a7f1c20806cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
