<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>90b7a190-4f2f-449d-9094-0a611bc4218e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38e4a6b8-2a06-4b42-aaf1-52f5f1d80922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo-white.png</value>
      <webElementGuid>5acddc27-ca7c-4894-aa07-2dc2f7ad2b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss4&quot;]/div[@class=&quot;layoutHeader_header_cim__1hvsL&quot;]/nav[1]/div[@class=&quot;layoutHeader_inner__ipM-g&quot;]/a[@class=&quot;layoutHeader_logo__8pZdM&quot;]/img[1]</value>
      <webElementGuid>00a5bc3b-2147-4ed2-8250-aab3d1cb859b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/div/a/img</value>
      <webElementGuid>b65ab018-11f3-44a1-bcc8-c1e436cef889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>021eb4de-4870-4072-8857-1db50c7f3072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/logo-white.png']</value>
      <webElementGuid>28b760ed-0990-473e-9069-110755b03e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
